#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace DataversePluginSample.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataversePluginSample.Model.kietec_Item"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataversePluginSample.Model.kietec_Item> kietec_ItemSet
		{
			get
			{
				return this.CreateQuery<DataversePluginSample.Model.kietec_Item>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataversePluginSample.Model.kietec_Resultado"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataversePluginSample.Model.kietec_Resultado> kietec_ResultadoSet
		{
			get
			{
				return this.CreateQuery<DataversePluginSample.Model.kietec_Resultado>();
			}
		}
	}
}
#pragma warning restore CS1591
